import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UseDataProvider } from "@/context/useDataContext"
import { UserChatProvider } from "@/context/UserChatContext";
import { MessageProvider } from "@/context/MessageNotification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MessageProvider>
          <UserChatProvider>
            <UseDataProvider>
              {children}
            </UseDataProvider>
          </UserChatProvider>
        </MessageProvider>
      </body>
    </html>
  );
}
